config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount GraphiQL::Rails::Engine, at: '/graphiql', graphql_path: '/graphql' if Rails.env.development?
  post '/graphql', to: 'graphql#execute'
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users, controllers: { registrations: 'user/registrations', sessions: 'user/sessions' }
    root to: 'main#index'
    resources 'organisation'
    resources 'team'
    namespace 'user' do
      resources 'conversations'
    end
  end
  namespace 'api' do
    namespace 'v1' do
      resources 'user'
    end
  end
end

app/models/organisation.rb
# frozen_string_literal: true

class Organisation < ApplicationRecord
  belongs_to :owner, class_name: 'User', foreign_key: :user_id
  validates_uniqueness_of :user_id
  has_many :users # , dependent: :destroy
  has_many :teams, dependent: :destroy
  validates :name, presence: true

  def users_from_organisation
    users = []
    teams.each do |team|
      users << team.users_teams.map(&:user)
    end
    users.flatten
  end
end

app/controllers/organisation_controller.rb
# frozen_string_literal: true

class OrganisationController < ApplicationController
  before_action :authenticate_user!
  before_action :set_organisation, only: [:show, :update, :edit, :destroy]
  before_action :owner_organisation?, only: [:edit, :update, :destroy]
  before_action :can_user_create_oranisation?, only: [:new, :create]
  skip_before_action :admin_need_to_create_organisation, only: [:new, :create]

  def index
    @organisations = Organisation.all.page(params[:page])
  end

  def show
    @users = @organisation.users_from_organisation
    @is_owner = Organisation::IsUserOrganisationOwnerService.new(@organisation, current_user).call
    return unless @organisation.nil?

    flash[:error] = t('record_doesnt_exist')
    redirect_to(organisation_index_path)
  end

  def new
    @organisation = Organisation.new
  end

  def create
    @organisation = Organisation.new(organisation_params)

    if @organisation.save
      session[:admin_has_organisation] = true
      flash[:success] = t('success_update')
      redirect_to(organisation_index_path)
    else
      flash.now[:error] = t('unsuccessful_update')
      render 'new'
    end
  end

  def edit; end

  def update
    if @organisation.update(organisation_params)
      flash[:success] = t('success_update')
      redirect_to(organisation_index_path)
    else
      flash.now[:error] = t('unsuccessful_update')
      render 'edit'
    end
  end

  private

  def organisation_params
    params[:organisation].permit(:name, :description).merge(user_id: current_user.id)
  end

  def set_organisation
    @organisation = Organisation.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:error] = t('record_doesnt_exist')
    redirect_to(organisation_index_path)
  end

  def owner_organisation?
    redirect_to(organisation_index_path) && return unless Organisation::IsUserOrganisationOwnerService.new(@organisation, current_user).call
  end

  def can_user_create_oranisation?
    redirect_to(organisation_index_path) && return unless current_user.is_admin && session[:admin_has_organisation] == false
  end
end

app/views/organisation/_form.html.erb
<%= bootstrap_form_for(@organisation, :url => { :action => yield(:form_action) }) do |form| %>
    <p>
      <%= form.text_field :name, label: t("name") %>
    </p>
   
    <p>
      <%= form.text_area :description, label: t("description") %>
    </p>
   
    <p>
      <%= form.submit yield(:button_text), class: "btn btn-info my-4" %>
    </p>
<% end %>

app/views/organisation/edit.html.erb
<% provide(:button_text, t('save_changes')) %>
<% provide(:form_action, :update) %>
  <div class="col-md-6 col-md-offset-3">
    <h1 class="display-4 pt-3 pb-3"><%= t('edit_organisation') %></h1>
    <%= render 'form' %>
  </div>

app/views/organisation/index.html.erb
<h1 class="display-4 pt-3 pb-3"><%= t('organisations') %></h1>
<div class="table-responsive table-organisation">
  <table class="table table-striped custom-table  mt-5">
    <thead class="bg-info text-white">
      <tr>
        <th class="text-center" scope="col">ID</th>
        <th class="text-center" scope="col"><%= t('name')%></th>
        <th class="text-center" scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @organisations.each do |organisation| %>
      <tr>
        <td class="text-center" scope="row"><%= organisation.id %></th>
        <td class="text-center"><%= organisation.name %></td>
        <td class="text-center"><%= link_to organisation_path(organisation) do %>
            <%= icon('fas', 'angle-double-right') %>
        <% end %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @organisations %>
</div>

app/views/organisation/new.html.erb
<% provide(:button_text, t('add_organisation')) %>
<% provide(:form_action, :create) %>

  <div class="col-md-6 col-md-offset-3">
    <h1 class="display-4 pt-3 pb-3"><%= t('add_organisation') %></h1>
    <%= render 'form' %>
  </div>

app/views/organisation/show.html.erb
<h1 class="display-4 pt-3 pb-3"><%=@organisation.name%></h1>

<div class="card border-info mb-3" style="max-width: 35rem;">
  <div class="card-header border-info"><%="#{t('owner_id')}: #{@organisation.owner.id}"%></div>
  <div class="card-header bg-transparent border-info">
    <p class="card-text"><%=@organisation.description%></p>
  </div>
  <div class="card-body bg-transparent border-info">
    <p class="font-weight-bold"><%= "#{t('users')}:" %></p>
    <% @users.each do |user| %>
        <p><%= user.email %></p>
    <% end %>
  </div>
</div>
  <% if @is_owner %>
    <%= link_to t("edit"), edit_organisation_path(@organisation), class: "btn btn-outline-info"  %>
  <% end %>