config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount GraphiQL::Rails::Engine, at: '/graphiql', graphql_path: '/graphql' if Rails.env.development?
  post '/graphql', to: 'graphql#execute'
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users, controllers: { registrations: 'user/registrations', sessions: 'user/sessions' }
    root to: 'main#index'
    resources 'organisation'
    resources 'team'
    namespace 'user' do
      resources 'conversations'
    end
  end
  namespace 'api' do
    namespace 'v1' do
      resources 'user'
    end
  end
end

app/models/conversation.rb
# frozen_string_literal: true

class Conversation < ApplicationRecord
  scope :by_conversation_members, ->(user_id) { joins(:conversation_members).where(conversation_members: { user_id: user_id }) }
  scope :conversation_initiator, ->(user_id) { where(initiator_id: user_id) }

  belongs_to :initiator, class_name: 'User', foreign_key: :initiator_id
  belongs_to :team, optional: true

  has_many :conversation_members, autosave: true
  accepts_nested_attributes_for :conversation_members, reject_if: :member_exists?, allow_destroy: true

  has_many :users, through: :conversation_members
  has_one_attached :image

  validates :subject, presence: true
  validates :note, presence: true
  validates :date, presence: true
  validates :initiator, presence: true
  # nested attr for

  enum status: [:active, :pending, :archived]
  Gutentag::ActiveRecord.call self

  # Return the tag names separated by a comma and space
  def tags_as_string
    tag_names.join(', ')
  end

  # Split up the provided value by commas and (optional) spaces.
  def tags_as_string=(string)
    self.tag_names = string.split(/,\s*/)
  end

  def self.search(term)
    if term
      tagged_with(names: term.split(/,\s*/), match: :any)
    else
      all
    end
  end

  def self.users_conversations(user)
    by_conversation_members(user) + conversation_initiator(user)
  end

  def member_exists?(attributes)
    !conversation_members.where(user_id: attributes['user_id']).empty?
  end
end

app/models/user.rb
# frozen_string_literal: true

# User model
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :email, uniqueness: true, presence: true

  has_many :users_teams, dependent: :destroy
  has_many :teams, through: :users_teams, dependent: :destroy
  has_one :organisation

  attr_accessor :team_id

  after_invitation_created :assign_user_to_team

  def full_name
    first_name + ' ' + last_name
  end

  def assign_user_to_team
    UsersTeam.create(user_id: id, team_id: team_id)
  end

  def user_organisation
    if is_admin
      Organisation.where(user_id: id).first
    else
      teams.first.organisation
    end
  end
end

app/controllers/api/v1/user_controller.rb
# frozen_string_literal: true

# User controller class
# frozen_string_literal: true.
module Api
  module V1
    class UserController < ApplicationController
      include Response
      include ExceptionHandler
      before_action :set_user, only: [:show, :update, :destroy]
      skip_before_action :verify_authenticity_token

      # GET /user
      def index
        @users = User.all
        render json: @users, each_serializer: UserSerializer
      end

      def show
        render json: @user
      end

      # POST /user
      def create
        @user = User.create!(user_params)
        render json: @user, status: :created
      end

      # PUT /user/:id
      def update
        @user.update(user_params)
        head :no_content
      end

      # DELETE /user/:id
      def destroy
        @user.destroy
        head :no_content
      end

      private

      def user_params
        # whitelist params
        params.permit(:first_name, :last_name, :age, :email, :password, :password_confirmation)
      end

      def set_user
        @user = User.find(params[:id])
      end

      def set_user_item
        @user = @user.items.find_by!(id: params[:id]) if @user
      end
    end
  end
end

app/controllers/user/conversations_controller.rb
# frozen_string_literal: true

class User
  class ConversationsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_conversation, only: [:show, :update, :edit, :destroy]
    before_action :initiator_of_conversation?, only: [:edit, :update, :destroy]
    before_action :conversation_member?, only: [:show]
    before_action :index_for_members_or_initiator, only: [:index]

    def index; end

    def show
      @is_initiator = Conversation::IsUserConversationMemberService.new(@conversation, current_user).initiator?

      return unless @conversation.nil?

      flash[:error] = t('record_doesnt_exist')
      redirect_to(user_conversations_path)
    end

    def new
      @conversation = Conversation.new
    end

    def create
      @conversation = Conversation.new(conversation_params)

      if @conversation.save
        Conversation::EmailInvitedUsersService.new(@conversation).call
        flash[:success] = t('success_update')
        redirect_to(user_conversations_path)
      else
        flash.now[:error] = t('unsuccessful_update')
        render 'new'
      end
    end

    def edit; end

    def update
      Conversation::MarkUsersForRemovalService.new(conversation_params, @conversation).call

      if @conversation.update(conversation_params)
        flash[:success] = t('success_update')
        redirect_to(user_conversations_path)
      else
        flash.now[:error] = t('unsuccessful_update')
        render 'edit'
      end
    end

    private

    def conversation_params
      params.require(:conversation)
            .permit(:subject, :note, :date, :status, :tags_as_string, :image,
                    conversation_members_attributes: [:id, :present_in_conversation, :user_id, '_destroy'])
            .merge(initiator_id: current_user.id)
    end

    def set_conversation
      @conversation = Conversation.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash[:error] = t('record_doesnt_exist')
      redirect_to(user_conversations_path)
    end

    def initiator_of_conversation?
      redirect_to(user_conversations_path) && return unless Conversation::IsUserConversationMemberService
                                                            .new(@conversation, current_user).initiator?
    end

    def conversation_member?
      redirect_to(user_conversations_path) && return unless Conversation::IsUserConversationMemberService
                                                            .new(@conversation, current_user).call || current_user.is_admin
    end

    def index_for_members_or_initiator
      return redirect_to(user_conversations_path(initiator: 'false')) unless params[:initiator].present?

      if params[:initiator] == 'true'
        index_for_members
      else
        index_for_initiators
      end
    end

    def index_for_members
      @conversations = Conversation.conversation_initiator(current_user.id).search(params[:term]).page(params[:page])
    end

    def index_for_initiators
      @conversations = Conversation.by_conversation_members(current_user.id).search(params[:term]).page(params[:page])
    end
  end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User
  class RegistrationsController < Devise::RegistrationsController
    def create
      super
      User::SetAsAdminService.new(resource).call
    end
  end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User
  class SessionsController < Devise::SessionsController
  end
end

app/helpers/user_helper.rb
# frozen_string_literal: true

module UserHelper
end

app/views/user/conversations/_form.html.erb
<%= bootstrap_form_for(@conversation, :url => { :action => yield(:form_action) }) do |form| %>
    <p>
      <%= form.text_field :subject, label: t("subject") %>
    </p>

    <p>
      <%= form.text_area :note, label: t("note") %>
    </p>

    <div class="file-input">
      <%= form.file_field :image, direct_upload: true, accept: "image/png,image/gif,image/jpeg", label: t("image")%>
    </div>


    

 <div class="form-group">
            <label for="date"><%=t("custom_date")%></label>
            <div class="input-group date" id="conversation_date" data-target-input="nearest">
                <input direct_upload="true" value="<%=@conversation.date.strftime('%d-%m-%Y %H-%M') if @conversation.date.present?%>" type="datetime" name="conversation[date]" class="form-control datetimepicker-input <% if @conversation.errors[:date].any?%>errors-sign<%end%>" data-target="#conversation_date" />
                <div class="input-group-append" data-target="#conversation_date" data-toggle="datetimepicker">
                    <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                </div>
            </div>
  </div> 
<div class="custom-errors"><%= @conversation.errors[:date].join(", ") if @conversation.errors[:date].any?%></div>


  
    <p>
      <%= form.select(:status, Conversation.statuses.keys.map {|key| [Conversation.human_enum_name(:status, key), key]}) %>
    </p>

    <div class="field">
      <%= form.text_field :tags_as_string, id: :product_tags_as_string, label: t("tags") %>
    </div>

    <%= form.fields_for :conversation_members_attributes do |ff| %>
      <% current_user.user_organisation.users_from_organisation.each do |user| %>
        <%= check_box_tag("conversation[conversation_members_attributes][][user_id]", user.id, Conversation::IsUserConversationMemberService.new(@conversation, user).call) %>
        <%= user.first_name %>
        <br>
      <% end %>
    <% end %>

    <p>
      <%= form.submit yield(:button_text), class: "btn btn-warning my-4" %>
      <%= link_to t('cancel'), user_conversations_path, class: "btn btn-outline-warning" %>
    </p>
<% end %>

app/views/user/conversations/edit.html.erb
<% provide(:button_text, t('save_changes')) %>
<% provide(:form_action, :update) %>

  <div class="col-md-6 col-md-offset-3">
    <h1 class="display-4 pt-3 pb-3"><%= t('edit_conversation') %></h1>
    <%= render 'form' %>
  </div>

app/views/user/conversations/index.html.erb
<h1 class="display-4 pt-3 pb-3"><%= t('conversations') %></h1>

 <%= link_to t('as_initiator'), user_conversations_path(initiator: "true"), class: "btn btn-warning" %>
  <%= link_to t('as_member'), user_conversations_path(initiator: "false"), class: "btn btn-warning" %>
<form class="form-inline float-md-right flex-nowrap">
<%= form_tag(user_conversations_path, method: "get")  do %>
  <%= hidden_field_tag :initiator, params[:initiator] %>
  <%= text_field_tag :term,  params[:term], placeholder: t('search-text'), class: "form-control mr-2" %>
  <%= submit_tag t('search'), class: "btn btn-warning  mr-2", name: nil %>
  <%= link_to t('all'), user_conversations_path(initiator: params[:initiator]), class: "btn btn-outline-warning" %>
<% end %>
</form>

<div class="table-responsive table-conversation">
  <table class="table table-striped custom-table  mt-5">
    <thead class="bg-warning text-white">
      <tr>
        <th class="text-center" scope="col"><%= t('subject')%></th>
        <th class="text-center" scope="col"><%= t('custom_date')%></th>
        <th class="text-center" scope="col"><%= t('tags')%></th>
        <th class="text-center" scope="col"><%= t('status')%></th>
        <th class="text-center" scope="col"></th>
      </tr>
    </thead>
    <tbody>
        <% @conversations.order(date: :asc).each do |conversation| %>
      <tr>
        <td class="text-center"><%= conversation.subject %></td>
          <td class="text-center"><%= conversation.date.to_s(:db)    %></td>
          <td class="text-center"><%= conversation.tags_as_string%>
          <td class="text-center"><%= Conversation.human_enum_name(:status, conversation.status) %></td>
          <td class="text-center"><%= link_to user_conversation_path(conversation) do %>
            <%= icon('fas', 'angle-double-right') %>
          <% end %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @conversations %>
</div> 

app/views/user/conversations/new.html.erb
<% provide(:button_text, t('add_conversation')) %>
<% provide(:form_action, :create) %>

  <div class="col-md-6 col-md-offset-3">
    <h1 class="display-4 pt-3 pb-3"><%= t('add_conversation') %></h1>
    <%= render 'form' %>
  </div>

app/views/user/conversations/show.html.erb
<h1 class="display-4 pt-3 pb-3"><%=@conversation.subject%></h1>

<div class="card border-warning mb-3" style="max-width: 35rem;">
  <div class="card-header border-warning"><%="#{t('initiator_id')}: #{@conversation.initiator.id}"%></div>
  <div class="card-header border-warning"><%="#{t('custom_date')}: #{@conversation.date}"%></div>
  <div class="card-header border-warning"><%="#{t('status')}: #{Conversation.human_enum_name(:status, @conversation.status)}"%></div>
  <div class="card-header border-warning"><%="#{t('tags')}: #{@conversation.tags_as_string}"%></div>
  <div class="card-body bg-transparent border-warning">
    <p class="card-text"><%=@conversation.note%></p>

  </div>

  <div class="card-body bg-transparent border-warning">
    <p class="font-weight-bold"><%= "#{t('members')}:" %></p>
    <% @conversation.users.each do |user| %>
        <p><%= user.first_name %></p>
  <% end %>
  </div>
    <% if @conversation.image.attached? %>
      <div class="card-body border-warning">
        <div style="width:400px; height:auto">
          <%= image_tag(@conversation.image, style: 'width:100%', class: "image") %>
        </div>
      </div>
    <% end %>
</div>

<% if @is_initiator %>
  <%= link_to t("edit"), edit_user_conversation_path(@conversation), class: "btn btn-outline-warning"  %>
<% end %>