config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount GraphiQL::Rails::Engine, at: '/graphiql', graphql_path: '/graphql' if Rails.env.development?
  post '/graphql', to: 'graphql#execute'
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users, controllers: { registrations: 'user/registrations', sessions: 'user/sessions' }
    root to: 'main#index'
    resources 'organisation'
    resources 'team'
    namespace 'user' do
      resources 'conversations'
    end
  end
  namespace 'api' do
    namespace 'v1' do
      resources 'user'
    end
  end
end

app/models/team.rb
# frozen_string_literal: true

class Team < ApplicationRecord
  has_many :users_teams, dependent: :destroy
  has_many :users, through: :users_teams, dependent: :destroy
  has_many :conversations, dependent: :destroy
  belongs_to :organisation
  validates :name, presence: true
end

app/controllers/team_controller.rb
# frozen_string_literal: true

class TeamController < ApplicationController
  before_action :authenticate_user!
  before_action :set_team, only: [:show, :update, :edit, :destroy]
  before_action :owner_organisation?, only: [:edit, :update, :destroy]

  def index
    @teams = current_user.user_organisation.teams.page(params[:page])
  end

  def show
    @is_owner = Organisation::IsUserOrganisationOwnerService.new(@team.organisation, current_user).call
    @users = @team.users
    return unless @team.nil?

    flash[:error] = t('record_doesnt_exist')
    redirect_to(team_index_path)
  end

  def new
    @team = Team.new
  end

  def create
    @team = Team.new(team_params)
    if @team.save
      flash[:success] = t('success_update')
      redirect_to(team_index_path)
    else
      flash.now[:error] = t('unsuccessful_update')
      render :new
    end
  end

  def edit; end

  def update
    if @team.update(team_params)
      flash[:success] = t('success_update')
      redirect_to(team_index_path)
    else
      flash.now[:error] = t('unsuccessful_update')
      render :edit
    end
  end

  private

  def team_params
    mother_organisation = Organisation.where(user_id: current_user.id).first
    params[:team].permit(:name, :description).merge(organisation_id: mother_organisation.id)
  end

  def set_team
    @team = Team.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:error] = t('record_doesnt_exist')
    redirect_to(team_index_path)
  end

  def owner_organisation?
    redirect_to(team_index_path) && return unless Organisation::IsUserOrganisationOwnerService.new(@team.organisation, current_user).call
  end
end

app/views/team/_form.html.erb
<%= bootstrap_form_for(@team, :url => { :action => yield(:form_action) }) do |form| %>
    <p>
      <%= form.text_field :name, label: t("name") %>
    </p>
   
    <p>
      <%= form.text_area :description, label: t("description") %>
    </p>
   
    <p>
      <%= form.submit yield(:button_text), class: "btn btn-success my-4" %>
    </p>
<% end %>

app/views/team/edit.html.erb
<% provide(:button_text, t('save_changes')) %>
<% provide(:form_action, :update) %>
  <div class="col-md-6 col-md-offset-3">
    <h1 class="display-4 pt-3 pb-3"><%= t('edit_team') %></h1>
    <%= render 'form' %>
  </div>

app/views/team/index.html.erb
<h1 class="display-4 pt-3 pb-3"><%= t('teams') %></h1>
<div class="table-responsive table-team">
  <table class="table table-striped custom-table  mt-5">
    <thead class="bg-success text-white">
      <tr>
        <th class="text-center" scope="col">ID</th>
        <th class="text-center" scope="col"><%= t('name')%></th>
        <th class="text-center" scope="col"></th>
      </tr>
    </thead>
    <tbody>
       <% @teams.each do |team| %>
      <tr>
        <td class="text-center" scope="row"><%=team.id%></th>
        <td class="text-center"><%= team.name %></td>
          <td class="text-center"><%= link_to team_path(team) do %>
              <%= icon('fas', 'angle-double-right') %>
          <% end %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
<%= paginate @teams %>
</div>

app/views/team/new.html.erb
<% provide(:button_text, t('add_team')) %>
<% provide(:form_action, :create) %>

  <div class="col-md-6 col-md-offset-3">
    <h1 class="display-4 pt-3 pb-3"><%= t('add_team') %></h1>
    <%= render 'form' %>
  </div>

app/views/team/show.html.erb
<h1 class="display-4 pt-3 pb-3"><%=@team.name%></h1>

<div class="card border-success mb-3" style="max-width: 35rem;">
  <div class="card-header border-success"><%="#{t('mother_organisation')}: #{@team.organisation.name}"%></div>
  <div class="card-header bg-transparent border-success">
    <p class="card-text"><%=@team.description%></p>
  </div>
  <div class="card-body bg-transparent border-success">
    <p class="font-weight-bold"><%= "#{t('users')}:" %></p>
    <% @users.each do |user| %>
        <p><%= user.email %></p>
    <% end %>
  </div>
</div>
<% if @is_owner %>
    <%= link_to t("edit"), edit_team_path(@team), class: "btn btn-outline-success"  %>
<% end %>