config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount GraphiQL::Rails::Engine, at: '/graphiql', graphql_path: '/graphql' if Rails.env.development?
  post '/graphql', to: 'graphql#execute'
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users, controllers: { registrations: 'user/registrations', sessions: 'user/sessions' }
    root to: 'main#index'
    resources 'organisation'
    resources 'team'
    namespace 'user' do
      resources 'conversations'
    end
  end
  namespace 'api' do
    namespace 'v1' do
      resources 'user'
    end
  end
end

app/views/layouts/_navigation_links.html.erb
<nav class="navbar navbar-expand-xl navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
            <li class="nav-item">
                <%= link_to t('conversations'), user_conversations_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to t('new_conversation'), new_user_conversation_path, class: "nav-link" %>
            </li> 
        <% end %>
        <% if user_signed_in? && current_user.is_admin %>
            <li class="nav-item">
                <%= link_to t("all_organisations"), organisation_index_path, class: "nav-link"%>
            </li>
            <li class="nav-item">
                <%= link_to t("all_teams"), team_index_path, class: "nav-link"%>
            </li>
            <li class="nav-item">
                <%= link_to t("new_team"), new_team_path, class: "nav-link"%>
            </li>
            <li class="nav-item">
                <%= link_to t("new_invitation"), new_user_invitation_path, class: "nav-link"%>
            </li>
        <% end %>
        <%= content_tag :li do %>
             <li class="nav-item">
                 <%= link_to t('to_en'), url_for(locale: 'en'), class: "nav-link" %>
            </li>
        <% end unless current_page?(locale: :en) %>
        
        <%= content_tag :li do %>
            <li class="nav-item">
                <%= link_to t('to_pl'), url_for(locale: 'pl'), class: "nav-link" %>
            </li>
        <% end unless current_page?(locale: :pl) %>
      </li>
              <% if current_user %>
            <li class="nav-item">
                <%= link_to t('sign_out'), destroy_user_session_path, method: :delete, class: "nav-link" %>
            </li>
             <% else %>
                <li class="nav-item">
                    <%= link_to t('sign_up'), new_user_registration_path, class: "nav-link" %>
                </li><li class="nav-item">
                    <%= link_to t('log_in'), new_user_session_path, class: "nav-link" %>
            </li>
            <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <%= render "layouts/navigation_links.html.erb" %>
    <main class="container">
      <% flash.each do |key, value| %>
        <% key = flash_class(key) %>
      <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </main>
  </body>
</html>